export const NEXT_DATE = "NEXT_DATE";
export const PREV_DATE = "PREV_DATE";
export const SET_CHART_NAME = "SET_CHART_NAME";
export const SET_SCROLL_TO_CHART = "SET_SCROLL_TO_CHART";
export const LOAD_WEATHER_DATA = "LOAD_WEATHER_DATA";
export const LOAD_WEATHER_DATA_SUCCESS = "LOAD_WEATHER_DATA_SUCCESS";
